name: CI

on: push

jobs:
  html5validator:
    runs-on: ubuntu-latest
    container: cyb3rjak3/html5validator:latest
    steps:
      - name: HTML5 Validator
        run: html5validator --also-check-css --format text index.html
