name: CI

on: push

jobs:
  html5validator:
    runs-on: ubuntu-latest
    container: cyb3rjak3/html5validator:latest
    steps:
      - name: HTML5 Validator
        run: html5validator --also-check-css --format text index.html
  bootlint:
    runs-on: ubuntu-latest
    container: node:slim
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        name: Cache yarn dependencies
        with:
          path: vendor/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --cache-folder vendor/yarn
      - name: Run bootlint
        run: yarn run bootlint index.html
